export const contactButtons = [
  {
    key: 1,
    content: 'All',
    as: 'a',
    icon:'users',
    size: 'small' as const,
    compact: true,
    className: 'all',
    functionArg: 'all',
  },
  {
    key: 2,
    content: 'In process',
    as: 'a',
    icon:'bolt',
    size: 'small' as const,
    compact: true,
    className: 'process',
    functionArg: 'inProcess',
  },
  {
    key: 3,
    content: 'Premium',
    as: 'a',
    icon:'star',
    size: 'small' as const,
    compact: true,
    className: 'premium',
    functionArg: 'premium',
  },
];

export const contactControls = [

  {
    key: 1,
    content:'',
    as:'a',
    icon: 'mail outline',
    size: 'small' as const,
    compact: true,
    className: 'mail',
    functionArg: 'mail',
  },
  // {
  //   key: 2,
  //   content:'',
  //   as:'',
  //   icon: 'share square',
  //   size: 'small' as const,
  //   compact: true,
  //   className: 'share',
  //   functionArg: 'share',
  // },
  {
    key: 3,
    content:'',
    as:'',
    icon: 'pencil',
    size: 'small' as const,
    compact: true,
    className: 'edit',
    functionArg: 'edit',
  },
  {
    key: 4,
    content: '',
    as:'',
    icon: 'eraser',
    size: 'small' as const,
    compact: true,
    className: 'delete',
    functionArg: 'delete',
  },
];

export const orderButtons = [
  {
    key: 1,
    content: 'All',
    as: '',
    size: 'small' as const,
    compact: true,
    className: 'active',
    functionArg: 'allOrders',
  },
  {
    key: 2,
    content: 'Sale',
    as: 'a',
    size: 'small' as const,
    compact: true,
    functionArg: 'saleOrders',
  },
  {
    key: 3,
    content: 'Purchase',
    as: 'a',
    size: 'small' as const,
    compact: true,
    functionArg: 'purchaseOrders',
  },
];

export const filterTasksButtons = [
  {
    key: 1,
    content: 'My',
    as: 'a',
    size: 'small' as const,
    compact: true,
    className: 'active',
    functionArg: 'myTasks',
  },
  {
    key: 2,
    content: 'Shared by me',
    as: 'a',
    size: 'small' as const,
    compact: true,
    functionArg: 'sharedByUser',
  },
  {
    key: 3,
    content: 'Shared with me',
    as: 'a',
    size: 'small' as const,
    compact: true,
    functionArg: 'sharedWithUser',
  },
];
export const filterSharedTasksButtons = [
  {
    key: 1,
    content: 'All',
    as: 'a',
    size: 'small' as const,
    id: 'all_shared',
    compact: true,
    className: 'active all-btn',
    functionArg: 'all',
  },
  {
    key: 2,
    content: 'Accepted',
    as: 'a',
    size: 'small' as const,
    compact: true,
    functionArg: 'acceptedTasks',
  },
  {
    key: 3,
    content: 'Refused',
    as: 'a',
    size: 'small' as const,
    compact: true,
    functionArg: 'refusedTasks',
  },
  {
    key: 4,
    content: 'Done',
    as: 'a',
    size: 'small' as const,
    compact: true,
    functionArg: 'doneTasks',
  },
];

export const filterLeads = [
  {
    key: 1,
    content:'All',
    as:'',
    active:true,
    size: 'small' as const,
    compact: true,
    className: 'all',
    functionArg: 'all',
    btnActive:'all'
  },
  {
    key: 2,
    content: 'Lead',
    as:'',
    size: 'small' as const,
    compact: true,
    className: 'lead',
    functionArg: 'lead',
    btnActive:'lead'
  },
  {
    key: 3,
    content: 'Opportunity',
    as:'',
    size: 'small' as const,
    compact: true,
    className: 'opportunity',
    functionArg: 'opportunity',
    btnActive:'opportunity'
  },
  {
    key: 4,
    content: 'Quote',
    as:'',
    size: 'small' as const,
    compact: true,
    className: 'quote',
    functionArg: 'quote',
    btnActive:'quote'
  },
  {
    key: 5,
    content: 'Invoice',
    as:'',
    size: 'small' as const,
    compact: true,
    className: 'invoice',
    functionArg: 'invoice',
    btnActive:'invoice'
  },
];

export const leadControls = [
  {
    key: 1,
    content:'',
    icon: 'edit outline',
    size: 'small' as const,
    compact: true,
    className: 'edit',
    functionArg: 'edit',
  },
  {
    key: 2,
    content:'',
    as:'a',
    icon: 'mail outline',
    size: 'small' as const,
    compact: true,
    className: 'mail',
    functionArg: 'mail',
  },
  {
    key: 3,
    content: '',
    as:'',
    icon: 'angle double up',
    size: 'small' as const,
    compact: true,
    className: 'upgrade',
    functionArg: 'upgrade',
  },
  {
    key: 4,
    content: '',
    as:'',
    icon: 'user cancel',
    size: 'small' as const,
    compact: true,
    className: 'abandon',
    functionArg: 'abandon',
  },
];
export const opportunityControls = [
  {
    key: 1,
    content:'',
    icon: 'edit outline',
    size: 'small' as const,
    compact: true,
    className: 'edit',
    functionArg: 'edit',
  },
  {
    key: 2,
    content: '',
    as:'a',
    icon: 'mail outline',
    size: 'small' as const,
    compact: true,
    className: 'mail',
    functionArg: 'mail',
  },
  {
    key: 3,
    content: '',
    as:'',
    icon: 'angle double up',
    size: 'small' as const,
    compact: true,
    className: 'upgrade',
    functionArg: 'upgrade',
  },
  {
    key: 4,
    content: '',
    as:'',
    icon: 'angle double down',
    size: 'small' as const,
    compact: true,
    className: 'downgrade',
    functionArg: 'downgrade',
  },
  {
    key: 5,
    content: '',
    as:'',
    icon: 'user cancel',
    size: 'small' as const,
    compact: true,
    className: 'abandon',
    functionArg: 'abandon',
  },
];
export const quoteControls = [
  {
    key: 1,
    content:'',
    icon: 'edit outline',
    size: 'small' as const,
    compact: true,
    className: 'edit',
    functionArg: 'edit',
  },
  {
    key: 2,
    content: '',
    as:'a',
    icon: 'mail outline',
    size: 'small' as const,
    compact: true,
    className: 'mail',
    functionArg: 'mail',
  },
  {
    key: 3,
    content: 'Invoice',
    as:'',
    icon: 'send',
    size: 'small' as const,
    compact: true,
    className: 'invoice',
    functionArg: 'upgrade',
  },
  {
    key: 4,
    content: '',
    as:'',
    icon: 'angle double down',
    size: 'small' as const,
    compact: true,
    className: 'downgrade',
    functionArg: 'downgrade',
  },
  {
    key: 5,
    content: '',
    as:'',
    icon: 'user cancel',
    size: 'small' as const,
    compact: true,
    className: 'abandon',
    functionArg: 'abandon',
  },
];
export const invoiceControls = [
  {
    key: 1,
    content:'',
    icon: 'edit outline',
    size: 'small' as const,
    compact: true,
    className: 'edit',
    functionArg: 'edit',
  },
  {
    key: 2,
    content: '',
    as:'a',
    icon: 'mail outline',
    size: 'small' as const,
    compact: true,
    className: 'mail',
    functionArg: 'mail',
  },
  {
    key: 3,
    content: 'Convert',
    as:'',
    icon: 'handshake outline',
    size: 'small' as const,
    compact: true,
    className: 'convert',
    functionArg: 'upgrade',
  },
  {
    key: 4,
    content: '',
    as:'',
    icon: 'angle double down',
    size: 'small' as const,
    compact: true,
    className: 'downgrade',
    functionArg: 'downgrade',
  },
  {
    key: 5,
    content: '',
    as:'',
    icon: 'user cancel',
    size: 'small' as const,
    compact: true,
    className: 'abandon',
    functionArg: 'abandon',
  },
];
